apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "ml-chart.name" . }}
  name: {{ include "ml-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ml-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ml-chart.name" . }}
    spec:
      containers:
      #メインコンテナの作成 
      - name: {{ .Values.mainContainer.name }}
        image: "{{ .Values.images.firstImage.repository }}:{{ .Values.images.firstImage.tag }}"
        volumeMounts: 
        - mountPath: /workspace/
          name: {{ .Values.Volumes.name }}
        workingDir: /workspace/
        tty: true

       #サイドカーコンテナの作成 今回はただの飾り
      - name: {{ .Values.sideContainer.name }}
        image: "{{ .Values.images.secondImage.repository }}:{{ .Values.images.secondImage.tag }}"
        tty: true 

      volumes:
        - name: {{ .Values.Volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.PVC.name }}
        
