kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.PV.name }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.PV.strage }}
  accessModes:
  - {{ .Values.PV.mode }}
  hostPath:
    #path: /Users/   #docker-desktopで使う場合、こちらをマウントする
    #path: /mnt/
    path: {{ .Values.PV.path }}