apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PVC.name }}
spec:
  storageClassName: manual
  accessModes:
  - {{ .Values.PVC.mode }}
  resources:
    requests:
      storage: {{ .Values.PVC.strage }}
  
  {{- if .Values.PVC.useStorageClass }}
  storageClassName: gp2  #<---　docker-desktopで使う場合はコメントアウトする
  {{- end -}}